import type { ResumeSectionConfig, ResumeSectionKey, ResumeTemplate, ResumeVisualConfig } from "./types";

export const resumeSections: ResumeSectionKey[] = [
  "personal",
  "summary",
  "objective",
  "experience",
  "education",
  "courses",
  "certifications",
  "technicalSkills",
  "softSkills",
  "languages",
  "projects",
  "portfolio",
  "links",
  "tools",
  "awards",
  "volunteer",
  "additional"
];

export const defaultSectionConfig: ResumeSectionConfig = {
  order: resumeSections,
  visibility: {
    personal: true,
    summary: true,
    objective: false,
    experience: true,
    education: true,
    courses: true,
    certifications: true,
    technicalSkills: true,
    softSkills: true,
    languages: true,
    projects: true,
    portfolio: true,
    links: true,
    tools: true,
    awards: true,
    volunteer: true,
    additional: true
  },
  titles: {
    personal: "Dados pessoais",
    summary: "Resumo profissional",
    objective: "Objetivo profissional",
    experience: "Experiência profissional",
    education: "Formação acadêmica",
    courses: "Cursos",
    certifications: "Certificações",
    technicalSkills: "Habilidades técnicas",
    softSkills: "Habilidades comportamentais",
    languages: "Idiomas",
    projects: "Projetos",
    portfolio: "Portfólio",
    links: "Links",
    tools: "Ferramentas",
    awards: "Premiações",
    volunteer: "Trabalho voluntário",
    additional: "Informações adicionais"
  }
};

export const defaultVisualConfig: ResumeVisualConfig = {
  primaryColor: "#4f46e5",
  secondaryColor: "#10b981",
  textColor: "#111827",
  backgroundColor: "#ffffff",
  titleFont: "Arial",
  bodyFont: "Arial",
  fontSize: 10,
  titleSize: 24,
  sectionSpacing: 16,
  lineSpacing: 1.45,
  margins: 15,
  borderStyle: "minimal",
  showIcons: false,
  showPhoto: false,
  photoShape: "circle",
  photoPosition: "left",
  headerBackground: false,
  sectionHighlight: true,
  density: "normal"
};

const visual = (overrides: Partial<ResumeVisualConfig>): ResumeVisualConfig => ({ ...defaultVisualConfig, ...overrides });

export const resumeTemplates: ResumeTemplate[] = [
  {
    id: "ats-limpo",
    name: "ATS Limpo",
    category: "ATS",
    description: "Modelo simples, uma coluna e texto selecionável para plataformas automáticas.",
    preview: "ats-clean",
    recommendedFor: "Gupy, Kenoby, Workday, Greenhouse, Indeed e candidaturas em massa.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 95,
    baseVisualScore: 70,
    baseRhScore: 85,
    atsRisk: "baixo",
    bestUse: "Candidatura automática, ATS e envio para plataformas online.",
    tags: ["ats", "limpo", "uma página", "candidatura em massa"],
    badges: ["Melhor para ATS", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#111827", secondaryColor: "#374151", showPhoto: false, sectionHighlight: false, density: "compacto" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "profissional-classico",
    name: "Profissional Clássico",
    category: "Profissional",
    description: "Estrutura tradicional, segura para RH e compatível com boa leitura automática.",
    preview: "classic",
    recommendedFor: "Administrativo, financeiro, atendimento, tecnologia e áreas corporativas.",
    recommendedLevel: "Júnior a sênior",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 90,
    baseVisualScore: 78,
    baseRhScore: 88,
    atsRisk: "baixo",
    bestUse: "Envio geral quando o usuário quer segurança e aparência profissional.",
    tags: ["clássico", "corporativo", "seguro"],
    badges: ["Melhor para RH", "Bom para ATS"],
    defaultVisualConfig: visual({ primaryColor: "#1d4ed8", secondaryColor: "#64748b", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "moderno-corporativo",
    name: "Moderno Corporativo",
    category: "Profissional",
    description: "Visual moderno com hierarquia clara e cores discretas.",
    preview: "corporate",
    recommendedFor: "Empresas, cargos analíticos, tecnologia, operações e gestão.",
    recommendedLevel: "Pleno a liderança",
    atsCompatible: true,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 82,
    baseVisualScore: 88,
    baseRhScore: 90,
    atsRisk: "baixo/médio",
    bestUse: "Envio manual e processos com leitura humana forte.",
    tags: ["moderno", "corporativo", "duas colunas"],
    badges: ["Melhor para RH", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#2563eb", secondaryColor: "#0f172a", showPhoto: false, headerBackground: true }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "comercial-vendas",
    name: "Comercial/Vendas",
    category: "Área",
    description: "Valoriza resultados, metas, negociação e atendimento.",
    preview: "sales",
    recommendedFor: "Vendas, SDR, pré-vendas, atendimento, consultor comercial e executivo de contas.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: true,
    baseAtsScore: 85,
    baseVisualScore: 85,
    baseRhScore: 90,
    atsRisk: "baixo/médio",
    bestUse: "Vagas comerciais e envio direto para recrutador.",
    tags: ["vendas", "comercial", "metas", "resultados"],
    badges: ["Melhor para RH", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#059669", secondaryColor: "#0f766e", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "marketing-criativo",
    name: "Marketing/Criativo",
    category: "Visual",
    description: "Visual forte para marketing, comunicação e áreas criativas, com aviso de risco ATS.",
    preview: "creative",
    recommendedFor: "Marketing, social media, design, comunicação e conteúdo.",
    recommendedLevel: "Júnior a sênior",
    atsCompatible: false,
    acceptsPhoto: true,
    hasBackground: true,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 65,
    baseVisualScore: 95,
    baseRhScore: 88,
    atsRisk: "médio",
    bestUse: "Envio direto por e-mail, WhatsApp ou recrutador humano.",
    tags: ["marketing", "criativo", "visual", "portfolio"],
    badges: ["Melhor visual", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#db2777", secondaryColor: "#7c3aed", showPhoto: true, headerBackground: true, sectionHighlight: true }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "tecnologia",
    name: "Tecnologia",
    category: "Área",
    description: "Prioriza habilidades técnicas, projetos, links e experiência objetiva.",
    preview: "tech",
    recommendedFor: "Desenvolvimento, suporte, dados, produto, QA e infraestrutura.",
    recommendedLevel: "Estágio a sênior",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: true,
    baseAtsScore: 90,
    baseVisualScore: 82,
    baseRhScore: 88,
    atsRisk: "baixo",
    bestUse: "ATS, plataformas técnicas e candidatura em massa.",
    tags: ["tecnologia", "projetos", "skills", "ats"],
    badges: ["Melhor para ATS", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#0ea5e9", secondaryColor: "#0f172a", showPhoto: false, density: "compacto" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "administrativo",
    name: "Administrativo",
    category: "Área",
    description: "Organizado, direto e claro para rotinas administrativas e atendimento interno.",
    preview: "admin",
    recommendedFor: "Assistente administrativo, escritório, recepção, financeiro e operações.",
    recommendedLevel: "Júnior a pleno",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 92,
    baseVisualScore: 76,
    baseRhScore: 86,
    atsRisk: "baixo",
    bestUse: "Plataformas de vagas e seleção tradicional.",
    tags: ["administrativo", "organizado", "ats"],
    badges: ["Melhor para ATS"],
    defaultVisualConfig: visual({ primaryColor: "#334155", secondaryColor: "#64748b", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "primeiro-emprego",
    name: "Primeiro Emprego",
    category: "Entrada",
    description: "Valoriza objetivo, formação, cursos, habilidades e projetos quando há pouca experiência.",
    preview: "first-job",
    recommendedFor: "Primeiro emprego e início de carreira.",
    recommendedLevel: "Sem experiência ou iniciante",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 88,
    baseVisualScore: 80,
    baseRhScore: 86,
    atsRisk: "baixo",
    bestUse: "Primeiras oportunidades e candidatura em massa.",
    tags: ["primeiro emprego", "habilidades", "cursos"],
    badges: ["Bom para candidatura em massa", "Melhor para ATS"],
    defaultVisualConfig: visual({ primaryColor: "#7c3aed", secondaryColor: "#10b981", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "estagio",
    name: "Estágio",
    category: "Entrada",
    description: "Destaca formação, disponibilidade, cursos e habilidades de aprendizado.",
    preview: "internship",
    recommendedFor: "Estágio, trainee e programas de entrada.",
    recommendedLevel: "Estudante",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 90,
    baseVisualScore: 78,
    baseRhScore: 84,
    atsRisk: "baixo",
    bestUse: "Programas em plataformas automáticas e vagas de estágio.",
    tags: ["estágio", "formação", "cursos"],
    badges: ["Melhor para ATS"],
    defaultVisualConfig: visual({ primaryColor: "#2563eb", secondaryColor: "#14b8a6", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "jovem-aprendiz",
    name: "Jovem Aprendiz",
    category: "Entrada",
    description: "Simples e amigável para jovens aprendizes, com foco em objetivo e cursos.",
    preview: "apprentice",
    recommendedFor: "Jovem aprendiz e vagas iniciais.",
    recommendedLevel: "Iniciante",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 88,
    baseVisualScore: 78,
    baseRhScore: 84,
    atsRisk: "baixo",
    bestUse: "Vagas de entrada e candidatura online.",
    tags: ["jovem aprendiz", "iniciante", "cursos"],
    badges: ["Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#16a34a", secondaryColor: "#2563eb", showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "operacional",
    name: "Operacional",
    category: "Área",
    description: "Direto e legível para funções operacionais, logística, indústria e serviços.",
    preview: "operations",
    recommendedFor: "Operacional, logística, produção, estoque, serviços e manutenção.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 92,
    baseVisualScore: 72,
    baseRhScore: 84,
    atsRisk: "baixo",
    bestUse: "Candidaturas em volume e seleção objetiva.",
    tags: ["operacional", "logística", "serviços"],
    badges: ["Melhor para ATS"],
    defaultVisualConfig: visual({ primaryColor: "#374151", secondaryColor: "#f59e0b", showPhoto: false, density: "compacto" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "executivo-lideranca",
    name: "Executivo/Liderança",
    category: "Executivo",
    description: "Valoriza resumo executivo, impacto, liderança, resultados e estratégia.",
    preview: "executive",
    recommendedFor: "Coordenação, gerência, liderança, supervisão e direção.",
    recommendedLevel: "Sênior e liderança",
    atsCompatible: true,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 78,
    baseVisualScore: 90,
    baseRhScore: 92,
    atsRisk: "baixo/médio",
    bestUse: "Envio direto e processos executivos.",
    tags: ["liderança", "executivo", "gestão", "resultados"],
    badges: ["Melhor para RH", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#111827", secondaryColor: "#b45309", showPhoto: false, headerBackground: true }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "minimalista",
    name: "Minimalista",
    category: "Profissional",
    description: "Visual limpo com pouco ruído e ótima legibilidade.",
    preview: "minimal",
    recommendedFor: "Qualquer área que precise de sobriedade e objetividade.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 93,
    baseVisualScore: 82,
    baseRhScore: 86,
    atsRisk: "baixo",
    bestUse: "ATS, e-mail e recrutadores que valorizam objetividade.",
    tags: ["minimalista", "limpo", "objetivo"],
    badges: ["Melhor para ATS", "Melhor para RH"],
    defaultVisualConfig: visual({ primaryColor: "#111827", secondaryColor: "#6b7280", sectionHighlight: false, showPhoto: false }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "com-foto",
    name: "Currículo com Foto",
    category: "Visual",
    description: "Modelo com foto opcional para envio direto, nunca obrigatório.",
    preview: "photo",
    recommendedFor: "Envio manual quando o usuário quiser apresentação mais pessoal.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: false,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 70,
    baseVisualScore: 90,
    baseRhScore: 84,
    atsRisk: "médio",
    bestUse: "WhatsApp, e-mail e recrutador humano.",
    tags: ["foto", "visual", "envio manual"],
    badges: ["Melhor visual", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#4f46e5", secondaryColor: "#10b981", showPhoto: true, photoPosition: "left" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "sem-foto",
    name: "Currículo sem Foto",
    category: "ATS",
    description: "Versão segura sem foto para seleção em massa e plataformas automáticas.",
    preview: "no-photo",
    recommendedFor: "ATS, candidatura automática, candidatura em massa e processos online.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 94,
    baseVisualScore: 74,
    baseRhScore: 84,
    atsRisk: "baixo",
    bestUse: "Versão principal para candidatura automática.",
    tags: ["sem foto", "ats", "seguro"],
    badges: ["Melhor para ATS", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#111827", secondaryColor: "#4b5563", showPhoto: false, density: "compacto" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "colorido-moderado",
    name: "Currículo Colorido Moderado",
    category: "Visual",
    description: "Cores moderadas sem perder profissionalismo.",
    preview: "color",
    recommendedFor: "Atendimento, comercial, marketing leve, educação e áreas híbridas.",
    recommendedLevel: "Júnior a pleno",
    atsCompatible: true,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 80,
    baseVisualScore: 90,
    baseRhScore: 86,
    atsRisk: "baixo/médio",
    bestUse: "Envio manual com bom equilíbrio visual.",
    tags: ["colorido", "moderado", "rh"],
    badges: ["Melhor visual", "Bom para envio manual"],
    defaultVisualConfig: visual({ primaryColor: "#7c3aed", secondaryColor: "#06b6d4", showPhoto: false, headerBackground: true }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "preto-branco",
    name: "Currículo Preto e Branco",
    category: "ATS",
    description: "Máxima simplicidade para impressão, leitura automática e sobriedade.",
    preview: "bw",
    recommendedFor: "Processos formais, impressão, ATS e envio universal.",
    recommendedLevel: "Todos os níveis",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: false,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 96,
    baseVisualScore: 68,
    baseRhScore: 82,
    atsRisk: "baixo",
    bestUse: "Candidatura em massa e versões limpas.",
    tags: ["preto e branco", "ats", "impressão"],
    badges: ["Melhor para ATS", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#000000", secondaryColor: "#444444", textColor: "#111111", showPhoto: false, sectionHighlight: false, density: "compacto" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "uma-pagina",
    name: "Currículo de Uma Página",
    category: "ATS",
    description: "Compacto para leitura rápida e perfis com conteúdo enxuto.",
    preview: "one-page",
    recommendedFor: "Estágio, primeiro emprego, júnior e candidatura em massa.",
    recommendedLevel: "Iniciante a júnior",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 94,
    baseVisualScore: 76,
    baseRhScore: 84,
    atsRisk: "baixo",
    bestUse: "Currículos curtos e objetivos.",
    tags: ["uma página", "compacto", "ats"],
    badges: ["Melhor para ATS", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#1f2937", secondaryColor: "#2563eb", showPhoto: false, density: "compacto", fontSize: 9, sectionSpacing: 10 }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "duas-paginas",
    name: "Currículo de Duas Páginas",
    category: "Profissional",
    description: "Mais espaço para histórico amplo sem perder organização.",
    preview: "two-page",
    recommendedFor: "Pleno, sênior, liderança e profissionais com várias experiências.",
    recommendedLevel: "Pleno a executivo",
    atsCompatible: true,
    acceptsPhoto: true,
    hasBackground: false,
    editableColors: true,
    oneColumn: true,
    twoColumns: false,
    baseAtsScore: 86,
    baseVisualScore: 82,
    baseRhScore: 88,
    atsRisk: "baixo",
    bestUse: "Perfis com conteúdo robusto e histórico longo.",
    tags: ["duas páginas", "sênior", "histórico"],
    badges: ["Melhor para RH"],
    defaultVisualConfig: visual({ primaryColor: "#1d4ed8", secondaryColor: "#475569", showPhoto: false, density: "normal" }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  },
  {
    id: "destaque-habilidades",
    name: "Currículo com Destaque em Habilidades",
    category: "Entrada",
    description: "Indicado quando há pouca experiência e boas competências, cursos ou projetos.",
    preview: "skills",
    recommendedFor: "Primeiro emprego, transição de carreira, tecnologia, estágio e jovem aprendiz.",
    recommendedLevel: "Iniciante a pleno",
    atsCompatible: true,
    acceptsPhoto: false,
    hasBackground: false,
    editableColors: true,
    oneColumn: false,
    twoColumns: true,
    baseAtsScore: 86,
    baseVisualScore: 84,
    baseRhScore: 86,
    atsRisk: "baixo/médio",
    bestUse: "Currículos com pouca experiência formal.",
    tags: ["habilidades", "transição", "primeiro emprego"],
    badges: ["Melhor para RH", "Bom para candidatura em massa"],
    defaultVisualConfig: visual({ primaryColor: "#7c3aed", secondaryColor: "#0ea5e9", showPhoto: false, sectionHighlight: true }),
    supportedSections: resumeSections,
    active: true,
    version: "1.0"
  }
];

export function getResumeTemplate(id?: string | null) {
  return resumeTemplates.find((template) => template.id === id) ?? resumeTemplates[0];
}
