export const INTEGRATION_ERRORS = {
  PROVIDER_DISABLED: "PROVIDER_DISABLED",
  PROVIDER_NOT_CONFIGURED: "PROVIDER_NOT_CONFIGURED",
  PROVIDER_AUTH_FAILED: "PROVIDER_AUTH_FAILED",
  PROVIDER_TOKEN_EXPIRED: "PROVIDER_TOKEN_EXPIRED",
  PROVIDER_CAPABILITY_NOT_AVAILABLE: "PROVIDER_CAPABILITY_NOT_AVAILABLE",
  PROVIDER_REQUIRES_PARTNER_ACCESS: "PROVIDER_REQUIRES_PARTNER_ACCESS",
  APPLICATION_SUBMIT_FAILED: "APPLICATION_SUBMIT_FAILED",
  JOB_NOT_FOUND: "JOB_NOT_FOUND",
  RESUME_NOT_FOUND: "RESUME_NOT_FOUND",
  USER_CONSENT_REQUIRED: "USER_CONSENT_REQUIRED",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED"
} as const;

export class IntegrationError extends Error {
  code: string;
  status: number;

  constructor(code: string, message: string, status = 400) {
    super(message);
    this.code = code;
    this.status = status;
  }
}
